---
# tasks file for add-elastic-repo

#Adding ELK repo.
- name: add elasticsearch public signing key
  apt_key: 
    url: "{{ elastic_psk_url }}"
    state: present

#install Transport module.
- name: installing apt-transport-https
  apt:
    name: apt-transport-https
    update_cache: yes

#add Elasticsearch repo definitions
- name: add elasticsearch repo definitions
  apt_repository:
    repo: "{{ elastic_repo }}"
    state: present

#update system
- name: updating system
  apt:
    update_cache: yes

