
---
# tasks file for elasticsearch

- name: installing elasticsearch
  apt:
    name: elasticsearch

#replace elasticsearch.yml file 
- name: replacing the config file elasticsearch
  template:
    src: elasticsearch.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0777

#starting elasticsearch service
- name: starting elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes

#xpacl security configuration:
#- name: including xpack security setup configuration
#  include: security/keystore.yml
