---
# tasks file for server
- name: install Apache2
  apt:
    name: apache2
    state: latest
    update_cache: yes
- name: deploy index.html on the server.
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root 
    mode: 0644
- name: Starting apache2.
  service: 
    name: apache2
    state: started
    enabled: yes
#in this playbook we install apache2 and deploy the index.html page on the server then we activate the service.
